import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  Packer,
} from "docx";
import { saveAs } from "file-saver";
import type { AnalysisResults } from "../../types";

function signalColorHex(signal: string): string {
  switch (signal) {
    case "bullish":
      return "22C55E";
    case "bearish":
      return "EF4444";
    default:
      return "A3A3A3";
  }
}

function buildQASections(results: AnalysisResults): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  if (!results.qa || results.qa.length === 0) return paragraphs;

  paragraphs.push(
    new Paragraph({
      text: "Q&A Analysis",
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 400, after: 200 },
    }),
  );

  for (const item of results.qa) {
    paragraphs.push(
      new Paragraph({
        text: item.question,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      }),
    );
    paragraphs.push(
      new Paragraph({
        children: [new TextRun({ text: item.answer })],
        spacing: { after: 100 },
      }),
    );
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Confidence: ${item.confidence}`,
            italics: true,
            size: 20,
            color: item.confidence === "high" ? "22C55E" : item.confidence === "medium" ? "EAB308" : "EF4444",
          }),
        ],
        spacing: { after: 200 },
      }),
    );
  }

  return paragraphs;
}

function buildStocksTable(results: AnalysisResults): (Paragraph | Table)[] {
  const elements: (Paragraph | Table)[] = [];
  if (!results.stocks || results.stocks.length === 0) return elements;

  elements.push(
    new Paragraph({
      text: "Stock Recommendations",
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 400, after: 200 },
    }),
  );

  const borderStyle = {
    style: BorderStyle.SINGLE,
    size: 1,
    color: "999999",
  };
  const borders = {
    top: borderStyle,
    bottom: borderStyle,
    left: borderStyle,
    right: borderStyle,
  };

  const headerCells = ["Ticker", "Company", "Market", "Signal", "Impact", "Reasoning"].map(
    (text) =>
      new TableCell({
        children: [
          new Paragraph({
            children: [new TextRun({ text, bold: true, size: 20 })],
            alignment: AlignmentType.LEFT,
          }),
        ],
        borders,
        width: { size: text === "Reasoning" ? 3000 : 1200, type: WidthType.DXA },
      }),
  );

  const dataRows = results.stocks.map(
    (s) =>
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: s.ticker, bold: true })] })],
            borders,
          }),
          new TableCell({
            children: [new Paragraph({ text: s.company })],
            borders,
          }),
          new TableCell({
            children: [new Paragraph({ text: s.market || "-" })],
            borders,
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: s.signal,
                    color: signalColorHex(s.signal),
                    bold: true,
                  }),
                ],
              }),
            ],
            borders,
          }),
          new TableCell({
            children: [new Paragraph({ text: String(s.impactScore) })],
            borders,
          }),
          new TableCell({
            children: [new Paragraph({ text: s.reasoning })],
            borders,
          }),
        ],
      }),
  );

  elements.push(
    new Table({
      rows: [new TableRow({ children: headerCells }), ...dataRows],
      width: { size: 100, type: WidthType.PERCENTAGE },
    }),
  );

  return elements;
}

export function exportAsDocx(results: AnalysisResults, title: string): void {
  const qaSections = buildQASections(results);
  const stocksSections = buildStocksTable(results);

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            text: title,
            heading: HeadingLevel.TITLE,
            spacing: { after: 300 },
          }),
          ...qaSections,
          ...stocksSections,
          new Paragraph({
            children: [
              new TextRun({
                text: "Generated by AlphaMarkets",
                italics: true,
                size: 18,
                color: "888888",
              }),
            ],
            spacing: { before: 600 },
          }),
        ],
      },
    ],
  });

  Packer.toBlob(doc).then((blob) => {
    saveAs(blob, `${title.replace(/[^a-zA-Z0-9_-]/g, "_")}.docx`);
  });
}
